name: Run Telegram Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'  # هر 10 دقیقه اجرا شود

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # تغییر مهم: TOKEN به BOT_TOKEN
      run: python bot.py
